name: markd
version: 2.1.3+7

description: A fork of dart-lang's markdown
authors:
- Dart Team <misc@dartlang.org>
- Tom Yeh <tomyeh@rikulo.org>
homepage: https://github.com/tomyeh/markd

executables:
  markdown:

environment:
  # sdk: '>=2.3.0 <3.0.0'
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  args: ^2.3.1
  charcode: ^1.3.1

dev_dependencies:
  build_runner: ^2.2.0
  build_version: ^2.1.1
  build_web_compilers: ^3.2.3
  collection: ^1.17.0
  expected_output: ^2.0.0
  html: ^0.15.1
  io: ^1.0.4
  js: ^0.6.5
  path: ^1.8.3
  pedantic: ^1.11.1
  test: ^1.21.4
  yaml: ^3.1.1
